### ISSUE TITLE
get_property_by_type return None for some type

### ISSUE THREAD

**Issue by Cyrix126** [kenianbei/vcard_parser#11]
I encounter an issue where `get_property_by_type` doesn't find the property for some types (tested on Email, Tel, Lang).

For example this code:
```
use vcard_parser::vcard::property::types::PropertyType;
use vcard_parser::vcard::Vcard;

fn main() {
let mut vcard = Vcard::default();
vcard.add_property("EMAIL:test@test.com").expect("Unable to add property.");
let _property = vcard.get_property_by_type(&PropertyType::Email).unwrap();
}
```

Will compile but if ran it will panic because 
`thread 'main' panicked at 'called Option::unwrap() on a None value', src/main.rs:7:66`

`get_property_by_type` return None where it should return the property just added.
The `add_property` works, if I return vcard as a string, I can see the new property. But for some reason the `get_property_by_type` can't retrieve it.

**Comment by kenianbei** [comment]
Hi, this is not obvious in the doc, but this method only works for single properties. For properties that have multiple cardinality like email, tel, you have to use get_properties_by_type.

I'm thinking about completely reworking how properties are matched, to more closely follow the spec, see https://github.com/kenianbei/vcard_parser/issues/8. I'll keep this issue open for now to discuss a better way to get properties from the vcard.

**Comment by Cyrix126** [comment]
ok, thanks for clearing that up.
