### ISSUE TITLE
get_value for type TEL include "tel:"

### ISSUE THREAD

**Issue by Cyrix126** [kenianbei/vcard_parser#12]
When using .get_value on a property of type TEL, it includes the `tel:`.

For example if a vcf file have a line like this (conformed as per https://www.rfc-editor.org/rfc/rfc6350#section-6.4.1)
`TEL;TYPE=cell;VALUE=uri:tel:1111111111`
property.get_value will return:
`tel:1111111111`
When _**I think**_ it should only return the numbers like what it is doing for this line:
`TEL;TYPE=cell;VALUE=uri:1111111111`
`1111111111`

**Comment by kenianbei** [comment]
TEL can store uri and textfield.  If you specify that the value type is a URI using the "VALUE=uri" parameter, the parser will parse it as a uri. If the uri is invalid (as per your last example), then it will parse it as text. Relevant code is here: https://github.com/kenianbei/vcard_parser/blob/main/src/vcard/properties/tel.rs

**Comment by Cyrix126** [comment]
ok, thanks. sorry for false alert, I wasn't sure if it was normal.
