### ISSUE TITLE
typo Langauge

### ISSUE THREAD

**Issue by Cyrix126** [kenianbei/vcard_parser#2]
Hi,

not important issue.

On file vcard/parameter/types.rs lines 12, 53 and 78.

```
vcard/parameter/types.rs:12:pub const PARAMETER_TYPE_LANGAUGE: &str = "LANGUAGE";
vcard/parameter/types.rs:54:            PARAMETER_TYPE_LANGAUGE => Ok(ParameterType::Language),
vcard/parameter/types.rs:78:            ParameterType::Language => PARAMETER_TYPE_LANGAUGE,
```

It seems to be a typo on the name of the parameter type. Should it be named  PARAMETER_TYPE_LANGUAGE instead of  PARAMETER_TYPE_LANGAUGE ?

**Comment by kenianbei** [comment]
Thanks, fixed.
