### ISSUE TITLE
Improve error handling and fallibility

### ISSUE THREAD

**Issue by Cyrix126** [kenianbei/vcard_parser#3]
Hi,

as per https://www.rfc-editor.org/rfc/rfc6350#section-5

 _Applications MUST ignore x-param and iana-param values they don't recognize._

When parsing a vcf file with a parameter X-PARAM:value

```
let file = "test.vcf"
let string = read_to_string(file);
let vcards = parse_to_vcards(string.as_str());
let vcard = vcards.first().unwrap();
```

The program panic with 'REASON: PropertyTypeUnknown("X-PARAM")'

Reason for X-param to be present:
https://www.rfc-editor.org/rfc/rfc6350#section-6.10

**Comment by kenianbei** [comment]
Yes, I haven't gotten around to doing this as the vcard_tui bin I'm using this lib with doesn't use x-param. I will probably get around to adding this, but defintely open to PRs.

**Comment by Cyrix126** [comment]
I made a [pull request](https://github.com/kenianbei/vcard_parser/pull/4)

I'm new to rust and just starting to write my own code after reading a lot of doc. Please be careful with my untested code.

**Comment by kenianbei** [comment]
I merged your PR, but after looking more closely at the issue, I decided to add a parsing function that will ignore properties that contain x-param, iana-tokens, and other custom params, rather than attempting to strip out x-params via regex. So you can now just use [parse_to_vcards_without_errors](https://docs.rs/vcard_parser/latest/vcard_parser/fn.parse_to_vcards_without_errors.html) or [Vcard::from](https://docs.rs/vcard_parser/latest/vcard_parser/vcard/struct.Vcard.html#method.from) to parse input that might contain custom props.

**Comment by Cyrix126** [comment]
I'm not sure that's the best way (my opinion only) . I think the new parser is a great idea and has its use, but it means that if I have another unknown field there will be no error.
If we stick to the specification, it says to ignore only x-params and iana-tokens, not another custom parameter.

If x-params and iana-params are valid (and to be ignored) in vcards, it should works with the first parser  [parse_to_vcards](https://docs.rs/vcard_parser/latest/vcard_parser/fn.parse_to_vcards.html) without errors or we could not make the difference between valid and invalid vcard if we need to use the [parse_to_vcards_without_errors](https://docs.rs/vcard_parser/latest/vcard_parser/fn.parse_to_vcards_without_errors.html).

For example in [vct](https://github.com/kenianbei/vcard_tui), I could expect my vcf file with x-params to be imported correctly, even if thoses x-params are not present in the ui. Right now it doesn't let me import it even if the rfc imply that it should ("must").

**Comment by kenianbei** [comment]
Good point. I think there is a lot more work to get this library compliant with the spec. The library currently either ignores all errors and only imports properties that are known and with valid parameters and values, or fails completely at the first error. 

A better approach is probably to only import valid properties, but return an array of errors that occurred during import. I think most applications that might use this library don't want the whole import process to fail at the first error.

**Comment by kenianbei** [comment]
This should be fixed in the most recent release as I added x-name and iana-token support.
